export { AssetsListPage } from './components/AssetsListPage'
export { AssetDetailPage } from './components/AssetDetailPage'
export { AssetFormPage } from './components/AssetFormPage'
export { AssetPricingPage } from './components/AssetPricingPage'
export { AssetFamiliesPage } from './components/AssetFamiliesPage'
export { AssetCategoriesPage } from './components/AssetCategoriesPage'
export { MachinesWorkspacePage } from './components/MachinesWorkspacePage'
